// car.service.ts
import { Injectable } from '@angular/core';
import { Car } from '../pages/car-list/car.model';

@Injectable({
  providedIn: 'root',
})
export class CarService {
  private cars: Car[] = [
    {
      id: 1,
      marka: 'Toyota Corolla',
      evjarat: 2021,
      uzemanyag: 'benzin',
      motor: '1.6 benzin',
      valto: 'automata',
      szemelyek: 5,
      fogyasztas_l_100km: 6.2,
      ar_nap_ft: 12000,
      autopalya_matrica: true,
      felszereltseg: ['klíma', 'GPS', 'tempomat', 'Bluetooth'],
    },
    {
      id: 2,
      marka: 'Volkswagen Golf',
      evjarat: 2020,
      uzemanyag: 'dízel',
      motor: '1.6 TDI',
      valto: 'manuális',
      szemelyek: 5,
      fogyasztas_l_100km: 5.1,
      ar_nap_ft: 13000,
      autopalya_matrica: true,
      felszereltseg: ['klíma', 'ülésfűtés', 'parkolószenzor'],
    },
    {
      id: 3,
      marka: 'Ford Focus',
      evjarat: 2019,
      uzemanyag: 'benzin',
      motor: '1.5 EcoBoost',
      valto: 'manuális',
      szemelyek: 5,
      fogyasztas_l_100km: 6.0,
      ar_nap_ft: 11500,
      autopalya_matrica: false,
      felszereltseg: ['klíma', 'Bluetooth'],
    },
    {
      id: 4,
      marka: 'Renault Clio',
      evjarat: 2022,
      uzemanyag: 'benzin',
      motor: '1.0 TCe',
      valto: 'automata',
      szemelyek: 5,
      fogyasztas_l_100km: 5.5,
      ar_nap_ft: 10000,
      autopalya_matrica: true,
      felszereltseg: ['klíma', 'GPS', 'automata fényszóró'],
    },
    {
      id: 5,
      marka: 'Opel Astra',
      evjarat: 2018,
      uzemanyag: 'dízel',
      motor: '1.6 CDTI',
      valto: 'manuális',
      szemelyek: 5,
      fogyasztas_l_100km: 5.7,
      ar_nap_ft: 12500,
      autopalya_matrica: false,
      felszereltseg: ['klíma', 'USB csatlakozó'],
    },
    {
      id: 6,
      marka: 'Skoda Octavia',
      evjarat: 2021,
      uzemanyag: 'dízel',
      motor: '2.0 TDI',
      valto: 'automata',
      szemelyek: 5,
      fogyasztas_l_100km: 4.9,
      ar_nap_ft: 13500,
      autopalya_matrica: true,
      felszereltseg: ['klíma', 'tempomat', 'tolatókamera'],
    },
    {
      id: 7,
      marka: 'Peugeot 208',
      evjarat: 2020,
      uzemanyag: 'benzin',
      motor: '1.2 PureTech',
      valto: 'manuális',
      szemelyek: 5,
      fogyasztas_l_100km: 5.2,
      ar_nap_ft: 9500,
      autopalya_matrica: false,
      felszereltseg: ['klíma', 'érintőképernyő'],
    },
    {
      id: 8,
      marka: 'Tesla Model 3',
      evjarat: 2023,
      uzemanyag: 'elektromos',
      motor: 'Long Range AWD',
      valto: 'automata',
      szemelyek: 5,
      fogyasztas_l_100km: 5.0,
      ar_nap_ft: 20000,
      autopalya_matrica: true,
      felszereltseg: ['klíma', 'GPS', 'tolatókamera', 'ülésfűtés', 'autopilot'],
    },
    {
      id: 9,
      marka: 'Hyundai Tucson',
      evjarat: 2022,
      uzemanyag: 'hibrid',
      motor: '1.6 Hybrid',
      valto: 'automata',
      szemelyek: 5,
      fogyasztas_l_100km: 5.6,
      ar_nap_ft: 16000,
      autopalya_matrica: true,
      felszereltseg: [
        'klíma',
        'tolatókamera',
        'Bluetooth',
        'vezetéstámogató rendszer',
      ],
    },
    {
      id: 10,
      marka: 'Mercedes-Benz Vito',
      evjarat: 2019,
      uzemanyag: 'dízel',
      motor: '2.2 CDI',
      valto: 'manuális',
      szemelyek: 8,
      fogyasztas_l_100km: 7.8,
      ar_nap_ft: 22000,
      autopalya_matrica: true,
      felszereltseg: ['klíma', 'tempomat', 'parkolóradar'],
    },
  ];

  getCars(): Car[] {
    return this.cars;
  }
}
